apiVersion: v1
kind: Service
metadata:
  name: myfinance-service
spec:
  type: LoadBalancer
  selector:
    app: myfinance
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000