apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfinance
  labels:
    app: myfinance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfinance
  template:
    metadata:
      labels:
        app: myfinance
    spec:
      volumes:
        - name: pvc-nfs
          persistentVolumeClaim:
            claimName: nfs
      containers:
      - name: backend
        image: BACKEND_IMAGE
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: "/app"
            name: pvc-nfs        
      - name: frontend
        image: FRONTEND_IMAGE
        ports:
        - containerPort: 80
          name: http-port