FROM python:3.8.6

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

RUN apt update && apt install -y vim

COPY .flaskenv application.db config.py runFlask.py /app/

COPY flask_backend /app/flask_backend/

EXPOSE 5000

CMD ["flask","run","--host=0.0.0.0"]