#Step 1
FROM node:10.22.1-alpine

USER root

RUN mkdir /app

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

RUN apk add curl && export MY_HOST_IP=`curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip`; (echo -n 'REACT_APP_MY_HOST_IP = ';echo $MY_HOST_IP) > .env

ENV NODE_OPTIONS --max_old_space_size=8192

EXPOSE 3000

RUN chmod +x node_modules/.bin/react-scripts && npm run build
