#Step 1
FROM node:10.22.1-alpine AS build-step

USER root

RUN mkdir /app

WORKDIR /app

COPY . /app

ENV NODE_OPTIONS --max_old_space_size=15360

EXPOSE 3000

RUN chmod +x node_modules/.bin/react-scripts && npm run build

#Step 2
FROM nginx:alpine

COPY --from=build-step /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
