#Step 1
FROM node:10.22.1-alpine

USER root

RUN mkdir /app

WORKDIR /app

COPY . /app

ENV NODE_OPTIONS --max_old_space_size=8192

EXPOSE 3000

RUN chmod +x node_modules/.bin/react-scripts

CMD ["npm","start"]

