#Step 1 
FROM romjacoby/myfinance_frontend_p1:latest AS build-step

#Step 2
FROM nginx:alpine

COPY --from=build-step /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
